#Spring datasource configs
spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 4

#report properties
report:
  generate: 0/5 13,18 * * ?
#generate: 0 0 18 LW * ?

#JiraIssues tasks cache refresh rate
cache:
  refresh-rate: 0 0 0 ? * *