#Spring datasource configs
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

#report properties
report:
  generate: 0 0/5 * * * *

#JiraIssues tasks cache refresh rate
cache:
  refresh-rate: 0 0/5 * * * *